# Generated by Django 3.0.4 on 2020-03-30 16:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Workout', max_length=120)),
                ('warmup_time', models.IntegerField(default=0)),
                ('cooldown_time', models.IntegerField(default=0)),
                ('laps', models.IntegerField(default=1)),
                ('exs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Exercise', max_length=63)),
                ('duration', models.IntegerField(default=30)),
                ('order', models.IntegerField(null=True)),
                ('preptime', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exrs', to='timing.Workout')),
            ],
        ),
    ]
