# Generated by Django 3.0.3 on 2020-03-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warmup_time', models.IntegerField(default=0)),
                ('cooldown_time', models.IntegerField(default=0)),
                ('laps', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30)),
                ('name', models.CharField(default='Exercise', max_length=63)),
                ('preptime', models.IntegerField(null=True)),
                ('exr_type', models.CharField(choices=[('for_reps', 'for reps'), ('for_time', 'for time')], max_length=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timing.Workout')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(default=30)),
                ('name', models.CharField(default='Break', max_length=63)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timing.Workout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
