# Generated by Django 3.0.4 on 2020-03-30 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=6), blank=True, size=None),
        ),
    ]
