# Generated by Django 3.0.4 on 2020-07-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='preptime',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
