# Generated by Django 3.0.4 on 2020-03-30 19:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0002_auto_20200330_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='order',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exs',
        ),
        migrations.AddField(
            model_name='workout',
            name='exrs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timing.Workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='preptime',
            field=models.IntegerField(default=0),
        ),
    ]
