# Generated by Django 3.0.4 on 2020-03-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0002_workout_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='preptime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
