# Generated by Django 3.0.4 on 2020-04-07 21:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timing', '0003_auto_20200330_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='exrs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
    ]
